### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by NargiT** [spring-projects/spring-plugin#36]
Hello,

I would like to know if the project is still maintained and if so, why I cannot find it in spring.io ?

Thx for answers

**Comment by olivergierke** [comment]
As you can see from the commit log, it's not dead. It just doesn't get any more attention as it's a rather tiny library with a very special focus. It's heavily used inside Spring (Data) projects and as far as we know in a couple of user applications directly.

Due to its strong focus, there's not too much to be done about it except casual maintenance or — as I am currently about to do — some upgrades to lift it to new generations of Java, Spring Framework etc.

**Comment by NargiT** [comment]
All right, I asked that because the project is not comming with the bom maven dependency.

**Comment by olivergierke** [comment]
Which BOM are you referring to? Spring Plugin is included in Spring Boot's dependency management, AFAIR.

**Comment by NargiT** [comment]
<groupId>org.springframework</groupId>
<artifactId>spring-framework-bom</artifactId>
<version>4.3.4.RELEASE</version>

this one

**Comment by olivergierke** [comment]
This is Spring Framework. Note that Spring Plugin resides in a different group (`org.springframework.plugin`), just as all other related projects do (HATEOAS, Data, Integration, Boot).
